version: '2'
services:
  api: &env_api
    build:
      context: .
      dockerfile: DockerFile
    command: npm run start
    ports:
      - "3000:3000"
    env_file: .env
    environment:
      - NPM_CONFIG_PREFIX=/node_modules
    volumes:
      - "npm_node_modules:/node_modules"
      - ./:/local-data-store
volumes:
  npm_node_modules: